### PR TITLE
Include missing header file

### PR DESCRIPTION
**Pull request by uaftab**
Include header file somehow missed for stringstream.

### CODE REVIEW

**Comment by grodtron** [comment]
huh, weird. Looks like nanomsg is missing somehow, I wonder what changed...

**Comment by uaftab** [comment]
Yeah the URL is changed for the nanomsg tarball. But I updated it the p4-behavioural-model repo in build/travis/install-nanomsg.sh. It passed the CI (at least the nanomsg part) so I merged in the commit 5ad9f3b. Not sure why the clone here is using the old nano-msg URL here in the setup.

**Comment by uaftab** [comment]
Ok Found the problem, it was cloning the branch "pfp" not master from the behavioural model

**Comment by uaftab** [comment]
Clang 3.5 - p4-behavioural-model compiled fine locally during pfp-p4 setup. Not sure why it errored here. Disabling check, merging and then reenabling check. Will look into it later.

**Pull request merged**
